on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: pull aditodesigner
      shell: bash
      run: docker pull qualityfirstsoftware/qftest-interactive
    
    - name: JDK
      uses: actions/setup-java@v3
      with:
        java-version: 13
        distribution: 'adopt'
    
    # ToDo: 
    # 1) change paths
    # -v ${{ github.workspace }}/container_workdir:/workdir 
    
    
    - name: run container
      shell: bash
      run: docker run -p 5901:5901 -v ${{ env.JAVA_HOME }}:/adito/java -v ${{ github.workspace }}/.github/workflows/uitest-action/QF-Test/license:/qftest/qftest-container/license -v ${{ github.workspace }}:/adito qualityfirstsoftware/qftest-interactive -batch -nomessagewindow -verbose errors,all -run /adito/.github/workflows/uitest-action/QF-Test/testsuites/exampleTestSuiteDesigner.qft
     
