on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: pull aditodesigner
      shell: bash
      run: docker pull adito/aditodesigner:2022.2.0.2
    
    - name: run container
      shell: bash
      run: docker run -d --name designer adito/aditodesigner:2022.2.0.2
      
    - name: solo
      shell: bash
      run: |
        docker exec designer pwd
        docker exec designer bash -c "cd .."
        docker exec designer pwd
        docker exec designer echo $JAVA_HOME
      
    - name: connected
      shell: bash
      run: |
        docker exec designer bash -c "pwd && \
        cd .. && \
        pwd"


  job_2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    container:
      image: adito/aditodesigner:2022.2.0.2
    steps:
    
    - name: run download qfs inside container
      run: pwd
      
    - name: run download qfs inside container
      run: cd ..
      
    - name: run download qfs inside container
      run: pwd
      
    - name: run download qfs inside container
      run: echo $JAVA_HOME
      
    - name: run download qfs inside container
      run: echo $PATH


  job_3:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    env:
        qfversion: '6.0.4'
    steps:
    
    - name: test1
      uses: addnab/docker-run-action@v3
      with:
        image: adito/aditodesigner:2022.2.0.2
        run: |
          pwd
          cd ..
          pwd
          echo $JAVA_HOME
          echo $PATH
          curl -o qftest.tar.gz "https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-${{ env.qfversion }}.tar.gz"
