on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: pull aditodesigner
      shell: bash
      run: docker pull adito/aditodesigner:2022.2.0.2
    
    - name: run container
      shell: bash
      run: docker run -d --name designer adito/aditodesigner:2022.2.0.2
      
    - name: run download qfs inside container
      shell: bash
      run: |
        docker exec designer pwd
        docker exec designer bash -c "cd .."
        docker exec designer pwd
      
    - name: run download qfs inside container
      shell: bash
      run: |
        docker exec designer pwd
        docker exec designer cd ..
        docker exec designer pwd


  job_2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    container:
      image: adito/aditodesigner:2022.2.0.2
    steps:
    
    - name: run download qfs inside container
      run: pwd
      
    - name: run download qfs inside container
      run: echo hi
      
    - name: run download qfs inside container
      run: echo $JAVA_HOME
      
    - name: run download qfs inside container
      run: echo $PATH
