on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: pull aditodesigner
      shell: bash
      run: docker pull qualityfirstsoftware/qftest-interactive
    
    # ToDo: 
    # 1) change paths
    # 2) install java 13
    # 2) add java 13 path to designer path
    # 3) add license
    # docker run -p 5901:5901 -v C:\0\license:/qftest/qftest-container/license -v C:\0:/adito -v C:\0\container_workdir:/workdir qualityfirstsoftware/qftest-interactive -batch -nomessagewindow -verbose errors,all -run /adito/.github/workflows/uitest-action/QF-Test/testsuites/linuxTestSuite.qft
    
    - run: echo $GITHUB_WORKSPACE
    
    - name: run container
      shell: bash
      run: docker run -p 5901:5901 qualityfirstsoftware/qftest-interactive -batch -nomessagewindow -verbose errors,all -run /qftest/qftest-container/demo/carconfig/carconfig_de.qft
     
