on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: pull aditodesigner
      shell: bash
      run: docker pull adito/aditodesigner:2022.2.0.2
    
    - name: run container
      shell: bash
      run: docker run -d --name designer adito/aditodesigner:2022.2.0.2
      
    - name: download qfs
      shell: bash
      run: |
        docker exec designer bash -c "curl -o qftest.tar.gz "https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-${{ env.qfversion }}.tar.gz""

    - name: install qfs
      shell: bash
      run: |
        docker exec designer bash -c "tar xzvf qftest.tar.gz && \
        cd qftest/qftest-${{ env.qfversion }} && \
        printf 'y\ny\n1024\ng\n' | ./setup.sh"

    - name: xvfb
      shell: bash
      run: |
        docker exec designer bash -c "sudo apt-get update"
        docker exec designer bash -c "printf 'y' | sudo apt-get upgrade"
        docker exec designer bash -c "printf 'y' | sudo apt install xvfb"
        docker exec designer bash -c "export DISPLAY=:1"
        docker exec designer bash -c "Xvfb :1 -screen 0 1600x1200x24 &"
        docker exec designer bash -c "echo $DISPLAY -> :1"

    - name: ui tests
      shell: bash
      run: |
        docker exec designer bash -c "qftest/qftest-${{ env.qfversion }}/bin/qftest -batch -nomessagewindow -verbose all,errors -run qftest/qftest-${{ env.qfversion }}/demo/carconfig/carconfig_de.qft"

