on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: pull aditodesigner
      shell: bash
      run: docker pull adito/aditodesigner:2022.2.0.2
    
    - name: run container
      shell: bash
      run: docker run -d --name designer adito/aditodesigner:2022.2.0.2
      
    - name: download qfs
      shell: bash
      run: |
        docker exec designer bash -c "\
        curl -o qftest.tar.gz "https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-${{ env.qfversion }}.tar.gz" && \
        tar xzvf qftest.tar.gz && \
        cd qftest/qftest-${{ env.qfversion }} && \
        printf 'y\ny\n1024\ng\n' | ./setup.sh && \
        ls"
